#!/usr/bin/python3
import json
import subprocess

CACHE = '/home/wpovell/.cache/polybar_mail'
def query():
    with open('/home/wpovell/dotfiles/pass.json') as f:
        p = json.load(f)
    with open(CACHE, 'r') as f:
        past = json.load(f)

    newPast = []
    f = open(CACHE, 'w')
        
    l = sorted(p.keys())[::-1]
    t = []

    try:
        for i, e in enumerate(l):
            obj = imaplib.IMAP4_SSL('imap.gmail.com', 993)
            obj.login(e, p[e])
            obj.select('Inbox', readonly=True)
            unread = list(map(lambda x: x.decode('utf-8'),
                              obj.search(None, 'UnSeen')[1][0].split()))
            t.append(unread)
            newMail = set(unread) - set(past[i])
            for i in newMail:
                m = obj.fetch(i, '(RFC822)')[1][0][1].decode('utf-8').split('\n')
                sub = None
                frm = None
                for line in m:
                    line = line.strip()
                    if line.startswith('Subject:'):
                        sub = line
                    if line.startswith('From:'):
                        frm = line
                    if sub and line:
                        break
                subprocess.call(['notify-send', 'Mail', '{}\n{}'.format(frm, sub)])
            obj.logout()
    except Exception as e:
        print(e)
    s = ''
    json.dump(t, f)
    lens = list(map(len, t))
    f.close()
    if sum(lens):
        s = '%{F' + altColor + '}'
    s += '  ' + '/'.join(map(str, lens))
    return s

def show():
    with open('/tmp/polybar_mail') as f:
        t = json.load(f)
    if t[1] or (t[1] == 0 and t[0] == 0):
        subprocess.call(['browser', 'mail.google.com/mail/u/0/'])
    if t[0]:
        subprocess.call(['browser', 'mail.google.com/mail/u/1/'])
    


import json, imaplib
from sys import argv
order = argv[1]
if order == 'query':
    altColor = argv[2]
    print(query())
else:
    show()
